---
- name: Testing andrewrothstein.arkade
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'arkade version'
      ansible.builtin.command: arkade version
      changed_when: false
      register: arkade_test_output
    - name: Output of 'arkade version'
      ansible.builtin.debug:
        msg: '{{ arkade_test_output.stdout }}'
