---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/arkade version
      register: arkade_test_output
    - name: arkade version
      debug:
        msg: '{{ arkade_test_output.stdout }}'
