---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: downloading {{ arkade_url }} to {{ arkade_install_exe }}
  become: true
  become_user: root
  get_url:
    url: '{{ arkade_url }}'
    dest: '{{ arkade_install_exe }}'
    checksum: '{{ arkade_checksum }}'
    mode: 0755
- name: linking {{ arkade_link }} to {{ arkade_install_exe }}
  become: true
  become_user: root
  file:
    src: '{{ arkade_install_exe }}'
    dest: '{{ arkade_link }}'
    state: link

